import type { Protocol, FeedItem, Study, MemberStory, TriggerData, HeatmapDay } from "./types";

export const PROTOCOLS: Protocol[] = [
  {
    id: "1",
    slug: "low-dose-naltrexone",
    emoji: "💊",
    title: "Low-Dose Naltrexone (LDN)",
    category: "Medication",
    evidenceLevel: "Moderate",
    reportCount: 847,
    summary: "Off-label use of naltrexone at 1.5–4.5mg nightly to modulate the immune response and reduce inflammation.",
    improvementRate: 68,
    tags: ["inflammation", "immune", "off-label"],
  },
  {
    id: "2",
    slug: "anti-inflammatory-diet",
    emoji: "🥗",
    title: "Anti-Inflammatory Diet Protocol",
    category: "Diet",
    evidenceLevel: "Moderate",
    reportCount: 1243,
    summary: "Elimination of nightshades, gluten, and seed oils combined with increased omega-3 intake from whole foods.",
    improvementRate: 54,
    tags: ["diet", "gut health", "omega-3"],
  },
  {
    id: "3",
    slug: "cold-water-therapy",
    emoji: "🧊",
    title: "Cold Water Therapy",
    category: "Physical",
    evidenceLevel: "Low",
    reportCount: 612,
    summary: "Daily cold showers or ice baths targeting joint inflammation through vasoconstriction and nervous system regulation.",
    improvementRate: 47,
    tags: ["inflammation", "physical", "recovery"],
  },
  {
    id: "4",
    slug: "sleep-optimization",
    emoji: "😴",
    title: "Sleep Optimization Protocol",
    category: "Lifestyle",
    evidenceLevel: "High",
    reportCount: 934,
    summary: "Strict sleep hygiene with dark/cool room, consistent schedule, and melatonin timing to reduce inflammatory markers.",
    improvementRate: 71,
    tags: ["sleep", "inflammation", "cortisol"],
  },
  {
    id: "5",
    slug: "vitamin-d-protocol",
    emoji: "☀️",
    title: "High-Dose Vitamin D3 + K2",
    category: "Supplements",
    evidenceLevel: "Moderate",
    reportCount: 1089,
    summary: "Vitamin D3 at 5,000–10,000 IU paired with K2 MK-7 to direct calcium and reduce immune dysregulation.",
    improvementRate: 62,
    tags: ["supplements", "immune", "vitamin D"],
  },
  {
    id: "6",
    slug: "stress-reduction-protocol",
    emoji: "🧘",
    title: "Stress Reduction Protocol",
    category: "Mind-Body",
    evidenceLevel: "Moderate",
    reportCount: 756,
    summary: "Daily meditation, breathwork, and HRV training shown to lower IL-6 and TNF-α levels in PsA patients.",
    improvementRate: 58,
    tags: ["stress", "mind-body", "HRV"],
  },
];

export const FEED_ITEMS: FeedItem[] = [
  {
    id: "1",
    source: "reddit",
    author: "u/psa_warrior_42",
    text: "Week 6 of LDN — morning stiffness went from 2 hours to under 20 minutes. This is the most significant improvement I've had in 3 years of trying every option my rheum suggested.",
    engagementCount: 312,
    timestamp: "2h ago",
    url: "https://www.reddit.com/r/PsoriaticArthritis/comments/1c3k9x2/week_6_ldn_update/",
  },
  {
    id: "2",
    source: "study",
    author: "Annals of Rheumatology",
    text: "New meta-analysis (n=2,847): Omega-3 supplementation reduces CRP by 24% and joint swelling scores by 18% in inflammatory arthritis patients. 18 RCTs included.",
    engagementCount: 89,
    timestamp: "4h ago",
    url: "https://pubmed.ncbi.nlm.nih.gov/38291847/",
  },
  {
    id: "3",
    source: "x",
    author: "@RheumNow",
    text: "Emerging data on sleep + PsA is hard to ignore. Patients who normalise sleep architecture show TNF-α reductions comparable to low-dose methotrexate in early disease. Sleep is medicine.",
    engagementCount: 1204,
    timestamp: "5h ago",
    url: "https://x.com/RheumNow/status/1776543210987654321",
  },
  {
    id: "4",
    source: "forum",
    author: "JointJourney_Sarah",
    text: "3 months nightshade-free. Skin plaques cleared ~70%, joint pain down significantly. Took about 8 weeks to notice anything. Don't give up in week 3 like I almost did.",
    engagementCount: 201,
    timestamp: "8h ago",
    url: "https://forums.arthritis.org/discussion/nightshade-elimination-3-month-update",
  },
  {
    id: "5",
    source: "reddit",
    author: "u/biologics_and_beyond",
    text: "Stacked cold therapy on top of my biologic. Added ~30% more relief than biologic alone. The combo seems synergistic — both morning and evening exposure seem to matter.",
    engagementCount: 178,
    timestamp: "12h ago",
    url: "https://www.reddit.com/r/PsoriaticArthritis/comments/1b8mz4t/cold_therapy_biologic_stack/",
  },
  {
    id: "6",
    source: "study",
    author: "Nature Immunology",
    text: "Sleep fragmentation increases TNF-α production by 40% in PsA models. The mechanism appears to be glial cell activation during sleep deprivation — a directly targetable pathway.",
    engagementCount: 203,
    timestamp: "14h ago",
    url: "https://pubmed.ncbi.nlm.nih.gov/38504671/",
  },
  {
    id: "7",
    source: "x",
    author: "@DrSarahRheum",
    text: "For patients asking about LDN: I'm now prescribing it as adjunct therapy for select PsA patients not achieving full remission on biologics. Anecdotally seeing 60-70% reporting improvement. Larger trial warranted.",
    engagementCount: 892,
    timestamp: "18h ago",
    url: "https://x.com/DrSarahRheum/status/1775998877665544333",
  },
  {
    id: "8",
    source: "reddit",
    author: "u/autoimmune_athlete",
    text: "6 months of strict AIP diet. Not a cure. But my DAS28 dropped from 4.2 to 2.1. My rheum was shocked. The dietary inflammation component is real and underestimated in treatment plans.",
    engagementCount: 445,
    timestamp: "20h ago",
    url: "https://www.reddit.com/r/PsoriaticArthritis/comments/1c1px9y/6_months_aip_das28_results/",
  },
  {
    id: "9",
    source: "forum",
    author: "Marcus_Remission",
    text: "Finally in clinical remission after 4 years. The stack that got me there: Humira + LDN 3mg + nightshade-free + consistent 8hr sleep + morning cold exposure. No single thing did it. It was all of them together.",
    engagementCount: 678,
    timestamp: "1d ago",
    url: "https://forums.arthritis.org/discussion/4-year-journey-to-remission",
  },
  {
    id: "10",
    source: "study",
    author: "Journal of Rheumatology",
    text: "Vitamin D levels inversely correlate with PsA disease activity (DAS28) in a cohort of 1,200 patients. Mean serum 25(OH)D in remission group: 67 ng/mL vs. 22 ng/mL in active disease group.",
    engagementCount: 156,
    timestamp: "1d ago",
    url: "https://pubmed.ncbi.nlm.nih.gov/37145823/",
  },
  {
    id: "11",
    source: "x",
    author: "@gut_immunology",
    text: "New sequencing data confirms Faecalibacterium prausnitzii depletion as a consistent signature in PsA. This is the same bug depleted in Crohn's. The gut-joint axis is real and dietary interventions may directly target it.",
    engagementCount: 731,
    timestamp: "2d ago",
    url: "https://x.com/gut_immunology/status/1774123456789012345",
  },
  {
    id: "12",
    source: "reddit",
    author: "u/vitamin_d_convert",
    text: "Was at 18 ng/mL vitamin D. Supplemented to 72 ng/mL over 6 months (10k IU D3 + K2). Joint pain reduced by roughly half. Skin almost completely clear. My rheum now checks D levels for all PsA patients.",
    engagementCount: 521,
    timestamp: "2d ago",
    url: "https://www.reddit.com/r/PsoriaticArthritis/comments/1bz3kq1/vitamin_d_levels_joint_pain_correlation/",
  },
];

export const STUDIES: Study[] = [
  {
    id: "1",
    slug: "omega3-inflammation-meta-2024",
    title: "Omega-3 Fatty Acids and Inflammatory Markers in Psoriatic Arthritis: A Systematic Review",
    journal: "Annals of Rheumatology",
    year: 2024,
    topic: "Diet",
    evidenceLevel: "High",
    summary: "Meta-analysis of 18 RCTs showing omega-3 supplementation reduces CRP by 24% and joint swelling scores by 18%.",
    url: "https://pubmed.ncbi.nlm.nih.gov/38291847/",
    isNew: true,
  },
  {
    id: "2",
    slug: "vitamin-d-immune-psa-2023",
    title: "Vitamin D Deficiency and Disease Activity in Psoriatic Arthritis: Cohort Study",
    journal: "Journal of Rheumatology",
    year: 2023,
    topic: "Supplements",
    evidenceLevel: "Moderate",
    summary: "Cohort of 1,200 PsA patients showing inverse correlation between serum 25(OH)D levels and DAS28 scores.",
    url: "https://pubmed.ncbi.nlm.nih.gov/37145823/",
    isNew: false,
  },
  {
    id: "3",
    slug: "sleep-tnf-alpha-2024",
    title: "Sleep Disruption as an Amplifier of TNF-α in Autoimmune Arthritis",
    journal: "Nature Immunology",
    year: 2024,
    topic: "Lifestyle",
    evidenceLevel: "High",
    summary: "Mechanistic study demonstrating sleep fragmentation increases TNF-α production by 40% in PsA mouse models.",
    url: "https://pubmed.ncbi.nlm.nih.gov/38504671/",
    isNew: true,
  },
  {
    id: "4",
    slug: "gut-microbiome-psa-2023",
    title: "Gut Microbiome Dysbiosis in Psoriatic Arthritis: Implications for Dietary Intervention",
    journal: "Gut",
    year: 2023,
    topic: "Diet",
    evidenceLevel: "Moderate",
    summary: "16S rRNA sequencing of 400 PsA patients reveals consistent reduction in Faecalibacterium prausnitzii vs. controls.",
    url: "https://pubmed.ncbi.nlm.nih.gov/36882291/",
    isNew: false,
  },
];

export const MEMBER_STORIES: MemberStory[] = [
  {
    id: "1",
    author: "Marcus T., 38",
    duration: "18 months",
    protocol: "LDN + Anti-inflammatory diet",
    improvement: "85% reduction in flares",
    excerpt: "I was unable to open jars or type for more than 20 minutes. After combining LDN with strict nightshade elimination, I completed a half-marathon last spring.",
    isFeatured: true,
  },
  {
    id: "2",
    author: "Priya S., 44",
    duration: "8 months",
    protocol: "Sleep protocol + Vitamin D",
    improvement: "Joint pain score: 8/10 → 2/10",
    excerpt: "The sleep optimization was the unlock for everything else. Once I fixed my sleep, the supplements actually started working.",
    isFeatured: false,
  },
  {
    id: "3",
    author: "David K., 52",
    duration: "14 months",
    protocol: "Cold therapy + stress reduction",
    improvement: "Off NSAIDs for 6 months",
    excerpt: "I was skeptical of cold showers. Now it's non-negotiable. Combined with meditation, my morning stiffness is essentially gone.",
    isFeatured: false,
  },
];

export const TRIGGERS: TriggerData[] = [
  { name: "Stress", percentage: 78 },
  { name: "Poor sleep", percentage: 71 },
  { name: "Nightshades", percentage: 58 },
  { name: "Alcohol", percentage: 52 },
  { name: "Seed oils", percentage: 44 },
  { name: "Sugar", percentage: 41 },
  { name: "Gluten", percentage: 38 },
  { name: "Dairy", percentage: 32 },
];

export function generateHeatmapData(): HeatmapDay[] {
  const days: HeatmapDay[] = [];
  const today = new Date();
  for (let i = 89; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(d.getDate() - i);
    days.push({
      date: d.toISOString().split("T")[0],
      intensity: (Math.floor(Math.random() * 5) as 0 | 1 | 2 | 3 | 4),
    });
  }
  return days;
}

export const SITE_STATS = {
  members: 14287,
  postsAnalyzed: 892400,
  protocols: 67,
  improvementRate: 73,
};
